### ISSUE TITLE
How i can add audio player?

### ISSUE THREAD

**Issue by sentoro** [therewasaguy/p5-music-viz#2]
Hello. I'm using this friquency http://therewasaguy.github.io/p5-music-viz/demos/04_fft_freq_spectrum/
and i need to add audioplayer on this page (for example - default html5 audio player). How i can do it?

**Comment by therewasaguy** [comment]
Hi @sentoro 

These examples use the Web Audio API, which exists separately from the HTML5 Audio element, and does not come with its own controls.

You can create your own controls for the p5.SoundFile using ``.play()``, ``.pause()`` and ``.stop()`` methods like [this example](http://p5js.org/learn/examples/Sound_Load_and_Play_Sound.php). You can use .currentTime to get the current position of the file, and getPeaks to make your own soundcloud-style player, like [this example](https://github.com/processing/p5.js-sound/blob/master/examples/waveform_peaks_with_playhead/sketch.js).

Alternately, it is also possible to use an HTML 5 Audio element. You would need to pipe it into the Web Audio API using [MediaElementAudioSource](http://webaudio.github.io/web-audio-api/#widl-AudioContext-createMediaElementSource-MediaElementAudioSourceNode-HTMLMediaElement-mediaElement). I'm going to make an example of this soon. In the meantime, it would be something like [this](http://stackoverflow.com/a/18215580/2994108), you'd connect put the Audio element into a MediaElementAudioSource, and then connect that to the FFT. I hope that's helpful.
