### ISSUE TITLE
Sometimes demos are not HTTPS

### ISSUE THREAD

**Issue by comfysquirrel** [therewasaguy/p5-music-viz#4]
Even though the links in the readme are https, sometimes when I open them they are not https in my browser (Chrome 53). I don't know what causes the browser to do this. Enabling [HTTPS Enforcement](https://github.com/blog/2186-https-for-github-pages) in the repo settings would fix it by always redirecting to https.

**Comment by therewasaguy** [comment]
good call, thanks @lasercar !
